use_frameworks!

platform :ios, '9.0'

target 'FomaViewableSound_Example' do
  pod 'FomaViewableSound', :path => '../'

  target 'FomaViewableSound_Tests' do
    inherit! :search_paths

    
  end
end
